title: I made a Thing
author: emjayking
email: emjayking23@hotmail.co.nz
description: > # this means to ignore newlines until "baseurl:"
  lookie here I did this thing. let's hope it works

# social links
twitter_username: your-twitter-handle
github_username:  emjayking

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
